################################################################################
#
# MUPEN64PLUS (Archived)
#
################################################################################

# Commit of 2019/07/05
LIBRETRO_MUPEN64PLUS_VERSION = ab8134ac90a567581df6de4fc427dd67bfad1b17
LIBRETRO_MUPEN64PLUS_SITE = $(call github,libretro,mupen64plus-libretro,$(LIBRETRO_MUPEN64PLUS_VERSION))
LIBRETRO_MUPEN64PLUS_LICENSE = GPL-2.0
LIBRETRO_MUPEN64PLUS_LICENSE_FILES = LICENSE

ifeq ($(BR2_PACKAGE_HAS_LIBGLES),y)
LIBRETRO_MUPEN64PLUS_NX_DEPENDENCIES += libgles
endif

ifeq ($(BR2_PACKAGE_HAS_LIBEGL),y)
LIBRETRO_MUPEN64PLUS_NX_DEPENDENCIES += libegl
endif

ifeq ($(BR2_PACKAGE_HAS_LIBGL),y)
LIBRETRO_MUPEN64PLUS_NX_DEPENDENCIES += libgl
endif

ifeq ($(BR2_i386)$(BR2_x86_64),y)
LIBRETRO_MUPEN64PLUS_DEPENDENCIES += host-nasm
endif

ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI3)$(BR2_PACKAGE_RECALBOX_TARGET_RPIZERO2LEGACY)$(BR2_PACKAGE_RECALBOX_TARGET_RPIZERO2),y)
LIBRETRO_MUPEN64PLUS_SUPP_OPT=FORCE_GLES=1 ARCH=arm
LIBRETRO_MUPEN64PLUS_PLATFORM=rpi3
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI5_64),y)
LIBRETRO_MUPEN64PLUS_SUPP_OPT=ARCH=aarch64
LIBRETRO_MUPEN64PLUS_PLATFORM=rpi4-mesa
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI4_64),y)
LIBRETRO_MUPEN64PLUS_SUPP_OPT=ARCH=aarch64
LIBRETRO_MUPEN64PLUS_PLATFORM=rpi4-mesa
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI4),y)
LIBRETRO_MUPEN64PLUS_SUPP_OPT=ARCH=arm
LIBRETRO_MUPEN64PLUS_PLATFORM=rpi4-mesa
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_ODROIDXU4),y)
LIBRETRO_MUPEN64PLUS_SUPP_OPT=FORCE_GLES=1 ARCH=arm
LIBRETRO_MUPEN64PLUS_PLATFORM=odroid
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_C2),y)
LIBRETRO_MUPEN64PLUS_SUPP_OPT=FORCE_GLES=1 ARCH=aarch64
LIBRETRO_MUPEN64PLUS_PLATFORM=unix
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_ODROIDGO2),y)
LIBRETRO_MUPEN64PLUS_SUPP_OPT=FORCE_GLES=1 ARCH=aarch64 GLFLAGS="-DHAVE_OPENGLES -DHAVE_OPENGLES2 -DGLES2 -DUSE_DEPTH_RENDERBUFFER -DEGL_NO_X11"
LIBRETRO_MUPEN64PLUS_PLATFORM=odroid64
else ifeq ($(BR2_i386),y)
LIBRETRO_MUPEN64PLUS_SUPP_OPT=ARCH=i686
LIBRETRO_MUPEN64PLUS_PLATFORM=unix
else ifeq ($(BR2_x86_64),y)
LIBRETRO_MUPEN64PLUS_SUPP_OPT=ARCH=x86_64
LIBRETRO_MUPEN64PLUS_PLATFORM=unix
else
LIBRETRO_MUPEN64PLUS_PLATFORM=$(RETROARCH_LIBRETRO_PLATFORM)
LIBRETRO_MUPEN64PLUS_SUPP_OPT=
endif

define LIBRETRO_MUPEN64PLUS_BUILD_CMDS
	CFLAGS="$(TARGET_CFLAGS)" CXXFLAGS="$(TARGET_CXXFLAGS)" \
		$(MAKE) NASM="$(HOST_DIR)/bin/nasm" CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" -C $(@D)/ -f Makefile platform="$(LIBRETRO_MUPEN64PLUS_PLATFORM)" $(LIBRETRO_MUPEN64PLUS_SUPP_OPT) \
		GIT_VERSION="$(shell echo $(LIBRETRO_MUPEN64PLUS_VERSION) | cut -c 1-8)"
endef

define LIBRETRO_MUPEN64PLUS_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/mupen64plus_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/mupen64plus_libretro.so
	mkdir -p $(TARGET_DIR)/recalbox/share_upgrade/bios/Mupen64plus/hires_texture
	mkdir -p $(TARGET_DIR)/recalbox/share_upgrade/bios/Mupen64plus/cache
endef

define LIBRETRO_MUPEN64PLUS_CROSS_FIXUP
	$(SED) 's|/opt/vc/include|$(STAGING_DIR)/usr/include|g' $(@D)/Makefile
	$(SED) 's|/opt/vc/lib|$(STAGING_DIR)/usr/lib|g' $(@D)/Makefile
endef

LIBRETRO_MUPEN64PLUS_PRE_CONFIGURE_HOOKS += LIBRETRO_MUPEN64PLUS_CROSS_FIXUP

$(eval $(generic-package))
