//
// Created by bkg2k on 22/11/24.
//
#include "MenuItemType.h"
#include <utils/storage/HashMap.h>
#include <utils/Log.h>

MenuContainerType MenuConverters::MenuFromString(const String& type)
{
  static const HashMap<String, MenuContainerType> sStringToMenuType
  {
    { "Main",                          MenuContainerType::Main },
    { "SystemSettings",                MenuContainerType::SystemSettings },
    { "StorageList",                   MenuContainerType::StorageList },
    { "StorageDevice",                 MenuContainerType::StorageDevice },
    { "Update",                        MenuContainerType::Update },
    { "Controllers",                   MenuContainerType::Controllers },
    { "CardReader",                    MenuContainerType::CardReader },
    { "Crt",                           MenuContainerType::Crt },
    { "RGBDual2",                      MenuContainerType::RGBDual2 },
    { "RGBJAMMA",                      MenuContainerType::RGBJAMMA },
    { "UI",                            MenuContainerType::UI },
    { "Screensaver",                   MenuContainerType::Screensaver },
    { "Theme",                         MenuContainerType::Theme },
    { "ThemeOptions",                  MenuContainerType::ThemeOptions },
    { "PopupSettings",                 MenuContainerType::PopupSettings },
    { "GameFilters",                   MenuContainerType::GameFilters },
    { "Lists",                         MenuContainerType::Lists },
    { "InGame",                        MenuContainerType::InGame },
    { "NetplayPasswords",              MenuContainerType::NetplayPasswords },
    { "Arcade",                        MenuContainerType::Arcade },
    { "Tate",                          MenuContainerType::Tate },
    { "Advanced",                      MenuContainerType::Advanced },
    { "BootSettings",                  MenuContainerType::BootSettings },
    { "VirtualSystems",                MenuContainerType::VirtualSystems },
    { "Resolutions",                   MenuContainerType::Resolutions },
    { "AdvancedEmulatorOptionsList",   MenuContainerType::AdvancedEmulatorOptionsList },
    { "Kodi",                          MenuContainerType::Kodi },
    { "Sound",                         MenuContainerType::Sound },
    { "Network",                       MenuContainerType::Network },
    { "Scraper",                       MenuContainerType::Scraper },
    { "Download",                      MenuContainerType::Download },
    { "Gamelist",                      MenuContainerType::Gamelist },
    { "Quit",                          MenuContainerType::Quit },
    { "ChooseKodiLobby",               MenuContainerType::ChooseKodiLobby },
    { "AdvancedSingleEmulatorOptions", MenuContainerType::AdvancedSingleEmulatorOptions},
    { "UserScripts",                   MenuContainerType::UserScripts },
    { "EditGame",                      MenuContainerType::EditGame },
    { "DeleteOptions",                 MenuContainerType::DeleteOptions },
    { "DeleteAdvanced",                MenuContainerType::DeleteAdvanced },
    { "SelectSoftpatch",               MenuContainerType::SelectSoftpatch },
    { "NetplayPasswords",              MenuContainerType::NetplayPasswords },
    { "NetplayHost",                   MenuContainerType::NetplayHost },
    { "NetplayClient",                 MenuContainerType::NetplayClient },
    { "EmulatorSpecificSettings",      MenuContainerType::EmulatorSpecificSettings },
  };
  if (type == "auto") { static int autoInc =0xFFFF; return (MenuContainerType)(++autoInc); }
  if (MenuContainerType* t = sStringToMenuType.try_get(type); t != nullptr) return *t;
  { LOG(LogFatal) << "[MenuProvider] Unknown menu ID " << type; }
  __builtin_unreachable();
}

static const HashMap<String, MenuItemType> sStringToItemType
{
  { "RecalboxVersion",              MenuItemType::RecalboxVersion },
  { "RecalboxArch",                 MenuItemType::RecalboxArch },
  { "UsedShare",                    MenuItemType::UsedShare },
  { "DeviceList",                   MenuItemType::DeviceList },
  { "ShareDevice",                  MenuItemType::ShareDevice },
  { "Language",                     MenuItemType::Language },
  { "TimeZone",                     MenuItemType::TimeZone },
  { "Keyboard",                     MenuItemType::Keyboard },
  { "Shutdown",                     MenuItemType::Shutdown },
  { "FastShutdown",                 MenuItemType::FastShutdown },
  { "Restart",                      MenuItemType::Restart },
  { "RunKodi",                      MenuItemType::RunKodi },
  { "OpenLobby",                    MenuItemType::OpenLobby },
  { "EnableKodi",                   MenuItemType::EnableKodi },
  { "KodiResolution",               MenuItemType::KodiResolution },
  { "KodiOnStartup",                MenuItemType::KodiOnStartup },
  { "KodiOnX",                      MenuItemType::KodiOnX },
  { "CheckBios",                    MenuItemType::CheckBios },
  { "ShowLicense",                  MenuItemType::ShowLicense },
  { "ScrapeFrom",                   MenuItemType::ScrapeFrom },
  { "ScrapeAuto",                   MenuItemType::ScrapeAuto },
  { "ScrapeOptionNameFrom",         MenuItemType::ScrapeOptionNameFrom },
  { "ScrapeOptionImage",            MenuItemType::ScrapeOptionImage },
  { "ScrapeOptionVideo",            MenuItemType::ScrapeOptionVideo },
  { "ScrapeOptionThumb",            MenuItemType::ScrapeOptionThumb },
  { "ScrapeOptionRegionPriority",   MenuItemType::ScrapeOptionRegionPriority },
  { "ScrapeOptionRegionFavorite",   MenuItemType::ScrapeOptionRegionFavorite },
  { "ScrapeOptionLanguageFavorite", MenuItemType::ScrapeOptionLanguageFavorite },
  { "ScrapeOptionManual",           MenuItemType::ScrapeOptionManual },
  { "ScrapeOptionMap",              MenuItemType::ScrapeOptionMap },
  { "ScrapeOptionP2K",              MenuItemType::ScrapeOptionP2K },
  { "ScrapeOptionUsername",         MenuItemType::ScrapeOptionUsername },
  { "ScrapeOptionPassword",         MenuItemType::ScrapeOptionPassword },
  { "ScrapeFilter",                 MenuItemType::ScrapeFilter },
  { "ScrapeSystems",                MenuItemType::ScrapeSystems },
  { "ScrapeRun",                    MenuItemType::ScrapeRun },
  { "Rewind",                       MenuItemType::Rewind },
  { "SoftPatching",                 MenuItemType::SoftPatching },
  { "ShowSaveStates",               MenuItemType::ShowSaveStates },
  { "AutoSave",                     MenuItemType::AutoSave },
  { "PressTwice",                   MenuItemType::PressTwice },
  { "SuperGameboyMode",             MenuItemType::SuperGameboyMode },
  { "GameRatio",                    MenuItemType::GameRatio },
  { "RecalboxOverlays",             MenuItemType::RecalboxOverlays },
  { "Smooth",                       MenuItemType::Smooth },
  { "IntegerScale",                 MenuItemType::IntegerScale },
  { "ShaderSet",                    MenuItemType::ShaderSet },
  { "AdvancedShaders",              MenuItemType::AdvancedShaders },
  { "HDMode",                       MenuItemType::HDMode },
  { "WideScreen",                   MenuItemType::WideScreen },
  { "AutoBlitter",                  MenuItemType::AutoBlitter },
  { "VulkanDriver",                 MenuItemType::VulkanDriver },
  { "Retroachievements",            MenuItemType::Retroachievements },
  { "RetroachievementsHardcore",    MenuItemType::RetroachievementsHardcore },
  { "RetroachievementsUsername",    MenuItemType::RetroachievementsUsername },
  { "RetroachievementsPassword",    MenuItemType::RetroachievementsPassword },
  { "Netplay",                      MenuItemType::Netplay },
  { "NetplayNickname",              MenuItemType::NetplayNickname },
  { "NetplayPort",                  MenuItemType::NetplayPort },
  { "NetplayRelay",                 MenuItemType::NetplayRelay },
  { "HashRoms",                     MenuItemType::HashRoms },
  { "Changelog",                    MenuItemType::Changelog },
  { "UpdateCheck",                  MenuItemType::UpdateCheck },
  { "UpdateAvailable",              MenuItemType::UpdateAvailable },
  { "UpdateChangelog",              MenuItemType::UpdateChangelog },
  { "UpdateStart",                  MenuItemType::UpdateStart },
  { "UpdateType",                   MenuItemType::UpdateType},
  { "UpdateCheckNow",               MenuItemType::UpdateCheckNow },
  { "NetworkStatus",                MenuItemType::NetworkStatus },
  { "NetworkHostname",              MenuItemType::NetworkHostname },
  { "NetworkIP",                    MenuItemType::NetworkIP },
  { "NetworkEnableWIFI",            MenuItemType::NetworkEnableWIFI },
  { "NetworkConnect",               MenuItemType::NetworkConnect },
  { "NetworkPickSSID",              MenuItemType::NetworkPickSSID },
  { "NetworkSSID",                  MenuItemType::NetworkSSID },
  { "NetworkPassword",              MenuItemType::NetworkPassword },
  { "NetworkWPS",                   MenuItemType::NetworkWPS },
  { "ShowOnlyLastVersions",         MenuItemType::ShowOnlyLastVersions },
  { "ShowOnlyFavorites",            MenuItemType::ShowOnlyFavorites },
  { "ShowFavoriteFirst",            MenuItemType::ShowFavoriteFirst },
  { "ShowHiddenGames",              MenuItemType::ShowHiddenGames },
  { "ShowMahjongCasino",            MenuItemType::ShowMahjongCasino },
  { "ShowAdultGames",               MenuItemType::ShowAdultGames },
  { "ShowPreinstalledGames",        MenuItemType::ShowPreinstalledGames },
  { "Show3PlayerGames",             MenuItemType::Show3PlayerGames },
  { "ShowOnlyYoko",                 MenuItemType::ShowOnlyYoko },
  { "ShowOnlyTate",                 MenuItemType::ShowOnlyTate },
  { "ShowNonGames",                 MenuItemType::ShowNonGames },
  { "ScreensaverTimeout",           MenuItemType::ScreensaverTimeout },
  { "ScreensaverType",              MenuItemType::ScreensaverType },
  { "ScreensaverSystems",           MenuItemType::ScreensaverSystems },
  { "PopupHelpDuration",            MenuItemType::PopupHelpDuration },
  { "PopupMusicOnOff",              MenuItemType::PopupMusic },
  { "PopupNetplayOnOff",            MenuItemType::PopupNetplay },
  { "ThemeManager",                 MenuItemType::ThemeManager },
  { "ThemeSet",                     MenuItemType::ThemeSet },
  { "ThemeCarousel",                MenuItemType::ThemeCarousel },
  { "ThemeTransition",              MenuItemType::ThemeTransition },
  { "GameTransition",               MenuItemType::GameTransition },
  { "ThemeRegion",                  MenuItemType::ThemeRegion },
  { "ThemeOptions",                 MenuItemType::ThemeOptions },
  { "Brightness",                   MenuItemType::Brightness },
  { "SystemSorting",                MenuItemType::SystemSorting },
  { "QuickSelectSystem",            MenuItemType::QuickSelectSystem },
  { "OnScreenHelp",                 MenuItemType::OnScreenHelp },
  { "SwapValidateCancel",           MenuItemType::SwapValidateCancel },
  { "OSDClock",                     MenuItemType::OSDClock },
  { "OneGameOneRom",                MenuItemType::OneGameOneRom },
  { "RomPreferredRegion",           MenuItemType::RomPreferredRegion },
  { "RomSecondPreferredRegion",     MenuItemType::RomSecondPreferredRegion },
  { "RomPreferredFallback",         MenuItemType::RomPreferredFallback },
  { "DisplayByFilename",            MenuItemType::DisplayByFilename },
  { "UpdateGamelists",              MenuItemType::UpdateGamelists },
  { "ShowSystems",                  MenuItemType::ShowSystems },
  { "ArcadeEnhancedView",           MenuItemType::ArcadeEnhancedView },
  { "ArcadeFoldClones",             MenuItemType::ArcadeFoldClones },
  { "ArcadeHideBios",               MenuItemType::ArcadeHideBios },
  { "ArcadeHideNonWorking",         MenuItemType::ArcadeHideNonWorking },
  { "ArcadeUseOfficielNames",       MenuItemType::ArcadeUseOfficielNames },
  { "ArcadeManufacturerSystems",    MenuItemType::ArcadeManufacturerSystems },
  { "ArcadeAggregateEnable",        MenuItemType::ArcadeAggregateEnable },
  { "ArcadeAggregateNeoGeo",        MenuItemType::ArcadeAggregateNeoGeo },
  { "ArcadeAggregateOriginal",      MenuItemType::ArcadeAggregateOriginal },
  { "BootOnKodi",                   MenuItemType::BootOnKodi },
  { "BootDoNotScan",                MenuItemType::BootDoNotScan },
  { "AllowBootOnGame",              MenuItemType::AllowBootOnGame },
  { "BootOnSystem",                 MenuItemType::BootOnSystem },
  { "BootOnGamelist",               MenuItemType::BootOnGamelist },
  { "BootShowVideo",                MenuItemType::BootShowVideo },
  { "HideSystemView",               MenuItemType::HideSystemView },
  { "VirtualAllGames",              MenuItemType::VirtualAllGames },
  { "VirtualMultiplayer",           MenuItemType::VirtualMultiplayer },
  { "VirtualLastPlayed",            MenuItemType::VirtualLastPlayed },
  { "VirtualLightgun",              MenuItemType::VirtualLightgun },
  { "VirtualPorts",                 MenuItemType::VirtualPorts },
  { "VirtualPerGenre",              MenuItemType::VirtualPerGenre },
  { "ResolutionGlobal",             MenuItemType::ResolutionGlobal },
  { "ResolutionFrontEnd",           MenuItemType::ResolutionFrontEnd },
  { "AdvDebugLogs",                 MenuItemType::AdvDebugLogs },
  { "AdvShowFPS",                   MenuItemType::AdvShowFPS },
  { "ResolutionEmulators",          MenuItemType::ResolutionEmulators },
  { "DeviceFreeSpace",              MenuItemType::DeviceFreeSpace },
  { "DeviceName",                   MenuItemType::DeviceName },
  { "DeviceFS",                     MenuItemType::DeviceFS },
  { "DeviceNetworkAccess",          MenuItemType::DeviceNetworkAccess },
  { "DeviceUsable",                 MenuItemType::DeviceUsable },
  { "DeviceInitialize",             MenuItemType::DeviceInitialize },
  { "WebManagerEnable",             MenuItemType::WebManagerEnable },
  { "FactoryReset",                 MenuItemType::FactoryReset },
  { "EmulatorsReset",               MenuItemType::EmulatorsReset },
  { "Overclock",                    MenuItemType::Overclock },
  { "PerSystemEmulator",            MenuItemType::PerSystemEmulator },
  { "PerSystemRatio",               MenuItemType::PerSystemRatio },
  { "PerSystemSmooth",              MenuItemType::PerSystemSmooth },
  { "PerSystemRewind",              MenuItemType::PerSystemRewind },
  { "PerSystemAutoLoadSave",        MenuItemType::PerSystemAutoLoadSave },
  { "PerSystemShaderSet",           MenuItemType::PerSystemShaderSet },
  { "PerSystemShaders",             MenuItemType::PerSystemShaders },
  { "PerSystemCrtHandheldFormat",   MenuItemType::PerSystemCrtHandheldFormat },
  { "CrtHandheldFormat",            MenuItemType::CrtHandheldFormat },
  { "BootloaderUpdate",             MenuItemType::BootloaderUpdate },
  { "CRVersion",                    MenuItemType::CRVersion },
  { "CRConsoleMode",                MenuItemType::CRConsoleMode },
  { "CRConsoleModeExitMode",        MenuItemType::CRConsoleModeExitMode },
  { "CRConsoleModeVideo",           MenuItemType::CRConsoleModeVideo },
  { "CRConsoleModeSound",           MenuItemType::CRConsoleModeSound },
  { "CrtAdapter",                   MenuItemType::CrtAdapter },
  { "CrtMenuResolution",            MenuItemType::CrtMenuResolution },
  { "CrtScreenType",                MenuItemType::CrtScreenType },
  { "CrtForced50hzDip",             MenuItemType::CrtForced50hzDip },
  { "CrtForced31kHzDip",            MenuItemType::CrtForced31kHzDip },
  { "CrtForcedCompositeDip",        MenuItemType::CrtForcedCompositeDip },
  { "CrtForceComposite",            MenuItemType::CrtForceComposite },
  { "CrtCompositeStandard",         MenuItemType::CrtCompositeStandard },
  { "CrtHDMIPriority",              MenuItemType::CrtHDMIPriority },
  { "CrtWideScreen",                MenuItemType::CrtWideScreen },
  { "CrtSelectRefreshAtLaunch",     MenuItemType::CrtSelectRefreshAtLaunch },
  { "CrtSelectResolutionAtLaunch",  MenuItemType::CrtSelectResolutionAtLaunch },
  { "CrtSelectSignalAtLaunch",      MenuItemType::CrtSelectSignalAtLaunch },
  { "CrtSuperrezMultiplier",        MenuItemType::CrtSuperrezMultiplier },
  { "CrtForceJack",                 MenuItemType::CrtForceJack },
  { "CrtScanline240in480",          MenuItemType::CrtScanline240in480 },
  { "CrtDemoAuto240",               MenuItemType::CrtDemoAuto240 },
  { "CrtAvoidInterlaced",           MenuItemType::CrtAvoidInterlaced },
  { "CrtAvoidLowFreqModes",         MenuItemType::CrtAvoidLowFreqModes },
  { "CrtAvoidInterlacedTateOnYokoAndHandhelds", MenuItemType::CrtAvoidInterlacedTateOnYokoAndHandhelds },
  { "JammaSound",                   MenuItemType::JammaSound },
  { "JammaAmpBoost",                MenuItemType::JammaAmpBoost },
  { "JammaPanelType",               MenuItemType::JammaPanelType },
  { "JammaNeogeoLayoutP1",          MenuItemType::JammaNeogeoLayoutP1 },
  { "JammaNeogeoLayoutP2",          MenuItemType::JammaNeogeoLayoutP2 },
  { "Jamma4PlayerMode",             MenuItemType::Jamma4PlayerMode },
  { "JammaCredit",                  MenuItemType::JammaCredit },
  { "JammaHotkey",                  MenuItemType::JammaHotkey },
  { "JammaVolume",                  MenuItemType::JammaVolume },
  { "JammaExit",                    MenuItemType::JammaExit },
  { "JammaAutoFire",                MenuItemType::JammaAutoFire },
  { "JammaDualJoystick",            MenuItemType::JammaDualJoystick },
  { "JammaPinE27",                  MenuItemType::JammaPinE27 },
  { "JammaReset",                   MenuItemType::JammaReset },
  { "CrtReducedLantency",           MenuItemType::CrtReducedLantency },
  { "CrtRunAhead",                  MenuItemType::CrtRunAhead },
  { "CrtScreenCalibration",         MenuItemType::CrtScreenCalibration },
  { "Case",                         MenuItemType::Case },
  { "UserScript",                   MenuItemType::UserScript },
  { "SoundSystemVolumem",           MenuItemType::SoundSystemVolumem },
  { "SoundMusicVolume",             MenuItemType::SoundMusicVolume },
  { "SoundAudioMode",               MenuItemType::SoundAudioMode },
  { "SoundAudioOutput",             MenuItemType::SoundAudioOutput },
  { "SoundBTPairing",               MenuItemType::SoundBTPairing },
  { "FlattenFolders",               MenuItemType::FlattenFolders },
  { "JumpToLetter",                 MenuItemType::JumpToLetter },
  { "SearchInSystem",               MenuItemType::SearchInSystem },
  { "SearchOtherVersion",           MenuItemType::SearchOtherVersions },
  { "SearchByLicence",              MenuItemType::SearchByLicence },
  { "SortGames",                    MenuItemType::SortGames },
  { "DecorateGames",                MenuItemType::DecorateGames },
  { "HighlightRegion",              MenuItemType::HighlightRegion },
  { "RunSaveStates",                MenuItemType::RunSaveStates },
  { "SetGameToBootOn",              MenuItemType::SetGameToBootOn },
  { "SetGameForCard",               MenuItemType::SetGameForCard },
  { "DeleteGame",                   MenuItemType::DeleteGame },
  { "MetadataSetEmulator",          MenuItemType::MetadataSetEmulator },
  { "MetadataSoftpatching",         MenuItemType::MetadataSoftpatching },
  { "MetadataRatio",                MenuItemType::MetadataRatio },
  { "MetadataName",                 MenuItemType::MetadataName },
  { "MetadataRating",               MenuItemType::MetadataRating },
  { "MetadataGenre",                MenuItemType::MetadataGenre },
  { "MetadataDescription",          MenuItemType::MetadataDescription },
  { "MetadataFavorite",             MenuItemType::MetadataFavorite },
  { "MetadataHidden",               MenuItemType::MetadataHidden },
  { "MetadataAdult",                MenuItemType::MetadataAdult },
  { "MetadataRotation",             MenuItemType::MetadataRotation },
  { "MetadataScrape",               MenuItemType::MetadataScrape },
  { "MetastatPlaytime",             MenuItemType::MetastatPlaytime },
  { "MetastatPlaycount",            MenuItemType::MetastatPlaycount },
  { "MetastatLastplayed",           MenuItemType::MetastatLastplayed },
  { "DeleteGameFiles",              MenuItemType::DeleteGameFiles },
  { "DeleteGameMedia",              MenuItemType::DeleteGameMedia },
  { "DeleteFileExtra",              MenuItemType::DeleteFileExtra },
  { "DeleteFileSaves",              MenuItemType::DeleteFileSaves },
  { "DeleteSelectGameFiles",        MenuItemType::DeleteSelectGameFiles },
  { "DeleteSelectGameMedia",        MenuItemType::DeleteSelectGameMedia },
  { "DeleteSelectFileExtra",        MenuItemType::DeleteSelectFileExtra },
  { "DeleteSelectFileSaves",        MenuItemType::DeleteSelectFileSaves },
  { "DeleteGo",                     MenuItemType::DeleteGo },
  { "DeleteCancel",                 MenuItemType::DeleteCancel },
  { "EnableFavorites",              MenuItemType::EnableFavorites },
  { "SoftpatchingRunOriginal",      MenuItemType::SoftpatchingRunOriginal },
  { "SoftpatchingRunPatched" ,      MenuItemType::SoftpatchingRunPatched },
  { "SoftpatchingSelectPatch",      MenuItemType::SoftpatchingSelectPatch },
  { "NetplayPassword",              MenuItemType::NetplayPassword },
  { "NetplayStart",                 MenuItemType::NetplayStart },
  { "NetplaySelectPlayerPassword",  MenuItemType::NetplaySelectPlayerPassword },
  { "NetplaySelectViewerPassword",  MenuItemType::NetplaySelectViewerPassword },
  { "NetplayCancel",                MenuItemType::NetplayCancel },
  { "NetplayJoinAsPlayer",          MenuItemType::NetplayJoinAsPlayer },
  { "NetplayJoinAsViewer",          MenuItemType::NetplayJoinAsViewer },
  { "NetplayUsePassword",           MenuItemType::NetplayUsePassword },
  { "DownloadGamePack",             MenuItemType::DownloadGamePack },
  { "MetadataLightgunsBoostLuminosity",     MenuItemType::MetadataLightgunsBoostLuminosity },
  { "ListFastMoveEnabled",          MenuItemType::ListFastMoveEnabled },
};

MenuItemType MenuConverters::ItemFromString(const String& type)
{
  if (MenuItemType* t = sStringToItemType.try_get(type); t != nullptr) return *t;
  { LOG(LogFatal) << "[MenuProvider] Unknown menu item ID " << type; }
  __builtin_unreachable();
}

String MenuConverters::ItemToString(MenuItemType type)
{
  for(const auto& kv : sStringToItemType)
    if (kv.second == type)
      return kv.first;
  return "Unknown";
}

