; ===========================
; Prince of Persia
; ===========================

[system]
uuid = "8b3b9053-463b-4d64-acea-7cd31d126209"
name = "princeofpersia"
fullname = "Prince of Persia"
theme.folder = "princeofpersia"
roms.folder = "%ROOT%/ports/Prince of Persia"
screenscraper.id = 135
doc.link.fr = "https://wiki.recalbox.com/fr/emulators/ports/prince-of-persia"
doc.link.en = "https://wiki.recalbox.com/en/emulators/ports/prince-of-persia"
port = 1
readonly = 0
icon.unicode = $F2f2
extension.types = "*=file"

[properties]
type = port
device.pad = mandatory
device.keyboard = no
device.mouse = no
device.lightgun = no
release.date = "1989-10"
manufacturer = "Brøderbund"
retroachievements = 0
crt.multiresolution = 1
crt.multiregion = 0

[core.0]
package = BR2_PACKAGE_SDLPOP
priority = 1
emulator = "sdlpop"
core = "sdlpop"
extensions = "files:prince of persia (1990).zip"
netplay = 0
softpatching = 0
compatibility = high
speed = high
crt.available = 1
