################################################################################
#
# kodi crunchyroll plugin
#
################################################################################

KODI_PLUGIN_VIDEO_CRUNCHYROLL_RELEASE = matrix
KODI_PLUGIN_VIDEO_CRUNCHYROLL_VERSION = matrix
KODI_PLUGIN_VIDEO_CRUNCHYROLL_PLUGINNAME = plugin.video.crunchyroll
KODI_PLUGIN_VIDEO_CRUNCHYROLL_SOURCE = $(KODI_PLUGIN_VIDEO_CRUNCHYROLL_VERSION).zip
KODI_PLUGIN_VIDEO_CRUNCHYROLL_SITE = https://github.com/smirgol/plugin.video.crunchyroll/archive
KODI_PLUGIN_VIDEO_CRUNCHYROLL_LICENSE = GNU Affero General Public License v3.0
KODI_PLUGIN_VIDEO_CRUNCHYROLL_LICENSE_FILES = $(KODI_PLUGIN_VIDEO_CRUNCHYROLL_PLUGINNAME)/README.md
KODI_PLUGIN_VIDEO_CRUNCHYROLL_DEPENDENCIES = kodi

KODI_PLUGIN_VIDEO_CRUNCHYROLL_TARGET_DIR=$(TARGET_DIR)/usr/share/kodi/addons/

define KODI_PLUGIN_VIDEO_CRUNCHYROLL_EXTRACT_CMDS
	@unzip -q -o $(DL_DIR)/kodi-plugin-video-crunchyroll/$(KODI_PLUGIN_VIDEO_CRUNCHYROLL_SOURCE) -d $(@D)
endef

define KODI_PLUGIN_VIDEO_CRUNCHYROLL_INSTALL_TARGET_CMDS
	@mkdir -p $(KODI_PLUGIN_VIDEO_CRUNCHYROLL_TARGET_DIR)
	@cp -r $(@D)/$(KODI_PLUGIN_VIDEO_CRUNCHYROLL_PLUGINNAME)-$(KODI_PLUGIN_VIDEO_CRUNCHYROLL_VERSION) $(KODI_PLUGIN_VIDEO_CRUNCHYROLL_TARGET_DIR)$(KODI_PLUGIN_VIDEO_CRUNCHYROLL_PLUGINNAME)/
endef

$(eval $(generic-package))
