; ===========================
; DICE
; ===========================

; all keys can be overridden for a particular board using key.<boardtag>
; example:
;   priority = 0
;   priority.rpi4 = 3
; Complete sections may be overridden. In such cases, all key from the global section are ignored,
; you must redefine them all
; example
; [core.0]
; [core.0.rpi4]
; Board tags are defined by BR2_PACKAGE_RECALBOX_TARGET_<tag>

[system]
uuid = "16F04331-6905-47D6-97FB-03F2042E7BD9"
name = "dice"
fullname = "DICE"
theme.folder = "dice"
roms.folder = "%ROOT%/dice"
; Atari Classics covers several of these games, start with that.
screenscraper.id = 160
doc.link.fr = "https://wiki.recalbox.com/fr/emulators/arcade/dice"
doc.link.en = "https://wiki.recalbox.com/en/emulators/arcade/dice"
doc.link.es = "https://wiki.recalbox.com/es/emulators/arcade/dice"
port = 0
readonly = 0
icon.unicode = $F2fb
extension.types = "*=cart"

[properties]
type = arcade
device.pad = mandatory
device.keyboard = no
device.mouse = optional
device.lightgun = no
release.date = "1972-01"
manufacturer = "DICE"
retroachievements = 0
crt.multiresolution = 0
crt.multiregion = 0

[core.0]
package = BR2_PACKAGE_LIBRETRO_DICE
priority = 1
emulator = "libretro"
core = "dice"
extensions = ".1da .4c .4d .6c .a1 .a4 .c4 .c6 .d2 .d4 .d7 .da1 .dmy .f4 .k1 .s1 .zip!"
netplay = 0
softpatching = 0
compatibility = high
speed = high
crt.available = 0
arcade.file = dice.lst
arcade.ignore =
