################################################################################
#
# YABASANSHIRO
#
################################################################################

# https://github.com/libretro/yabause/tree/yabasanshiro/yabause/src/libretro
# Commit of 2025/12/20
LIBRETRO_YABASANSHIRO_VERSION = d2afc930613744ee7bea600bde8c9558f68dba60
LIBRETRO_YABASANSHIRO_SITE = $(call github,libretro,yabause,$(LIBRETRO_YABASANSHIRO_VERSION))
LIBRETRO_YABASANSHIRO_LICENSE = GPL-2.0

ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_ODROIDXU4),y)
LIBRETRO_YABASANSHIRO_PLATFORM=odroid
LIBRETRO_YABASANSHIRO_SUPP_OPT=BOARD="ODROID-XU4"
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_ODROIDGO2),y)
LIBRETRO_YABASANSHIRO_PLATFORM=odroid-go2
LIBRETRO_YABASANSHIRO_LDFLAGS_OPT = -lpthread
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RG353X),y)
LIBRETRO_YABASANSHIRO_PLATFORM=arm64
LIBRETRO_YABASANSHIRO_SUPP_OPT = FORCE_GLES=1
LIBRETRO_YABASANSHIRO_LDFLAGS_OPT = -lpthread
else
LIBRETRO_YABASANSHIRO_PLATFORM=$(RETROARCH_LIBRETRO_BOARD_SHORT)
LIBRETRO_YABASANSHIRO_SUPP_OPT=
endif

ifeq ($(BR2_PACKAGE_RECALBOX_HAS_LIBMALI),y)
LIBRETRO_YABASANSHIRO_LDFLAGS_OPT += -lmali
endif

define LIBRETRO_YABASANSHIRO_DOSUNIX_PATCH
	$(SED) 's/\r//' $(@D)/yabause/src/yglshaderes.c
endef

LIBRETRO_YABASANSHIRO_PRE_PATCH_HOOKS += LIBRETRO_YABASANSHIRO_DOSUNIX_PATCH

define LIBRETRO_YABASANSHIRO_BUILD_CMDS
	$(SED) "s|-O2|-O3|g" $(@D)/yabause/src/libretro/Makefile
	CFLAGS="$(TARGET_CFLAGS) $(COMPILER_COMMONS_CFLAGS_NOLTO)" \
		CXXFLAGS="$(TARGET_CXXFLAGS) $(COMPILER_COMMONS_CXXFLAGS_NOLTO)" \
		LDFLAGS="$(TARGET_LDFLAGS) $(COMPILER_COMMONS_LDFLAGS_NOLTO) $(LIBRETRO_YABASANSHIRO_LDFLAGS_OPT)" \
		$(MAKE) CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" AR="$(TARGET_AR)" LD="$(TARGET_LD)" RANLIB="$(TARGET_RANLIB)" -C $(@D)/yabause/src/libretro -f Makefile platform="$(LIBRETRO_YABASANSHIRO_PLATFORM)" $(LIBRETRO_YABASANSHIRO_SUPP_OPT) \
		GIT_VERSION="-$(shell echo $(LIBRETRO_YABASANSHIRO_VERSION) | cut -c 1-8)"
endef

define LIBRETRO_YABASANSHIRO_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/yabause/src/libretro/yabasanshiro_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/yabasanshiro_libretro.so
	mkdir -p $(TARGET_DIR)/recalbox/share_upgrade/bios/saturn
endef

$(eval $(generic-package))
