################################################################################
#
# DOLPHIN_EMU
#
################################################################################

# Commit of 2025/09/19
DOLPHIN_EMU_SITE = https://github.com/dolphin-emu/dolphin.git
DOLPHIN_EMU_VERSION = 79614956f39fc1f6d47ff3fcf6484ef19f4e1ae4
DOLPHIN_EMU_LICENSE = GPL-2.0+
DOLPHIN_EMU_LICENSE_FILES = license.txt
DOLPHIN_EMU_DEPENDENCIES = libevdev ffmpeg zlib libpng lzo libusb libcurl bluez5_utils hidapi xz host-xz sdl2 qt6base qt6svg
DOLPHIN_EMU_SUPPORTS_IN_SOURCE_BUILD = NO
DOLPHIN_EMU_SITE_METHOD = git
DOLPHIN_EMU_GIT_SUBMODULES = YES

DOLPHIN_EMU_CONF_OPTS  = -DCMAKE_BUILD_TYPE=Release
DOLPHIN_EMU_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
DOLPHIN_EMU_CONF_OPTS += -DDISTRIBUTOR='Recalbox'
DOLPHIN_EMU_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
DOLPHIN_EMU_CONF_OPTS += -DUSE_MGBA=OFF
DOLPHIN_EMU_CONF_OPTS += -DUSE_UPNP=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_TESTS=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_AUTOUPDATE=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_ANALYTICS=OFF
DOLPHIN_EMU_CONF_OPTS += -DUSE_SYSTEM_LIBS=AUTO
DOLPHIN_EMU_CONF_OPTS += -DENABLE_CLI_TOOL=OFF
DOLPHIN_EMU_CONF_OPTS += -DUSE_RETRO_ACHIEVEMENTS=ON

DOLPHIN_EMU_CONF_OPTS += -DENABLE_QT=ON
DOLPHIN_EMU_CONF_OPTS += -DENABLE_NOGUI=ON

DOLPHIN_EMU_MAKE_ENV += LDFLAGS="-Wl,--copy-dt-needed-entries"
DOLPHIN_EMU_CONF_ENV += LDFLAGS="-Wl,--copy-dt-needed-entries"

ifeq ($(BR2_PACKAGE_RECALBOX_VIDEO_XORG_SERVER),y)
DOLPHIN_EMU_DEPENDENCIES += xserver_xorg-server
DOLPHIN_EMU_CONF_OPTS += -DENABLE_X11=ON
endif

ifeq ($(BR2_PACKAGE_RECALBOX_VIDEO_XWAYLAND),y)
DOLPHIN_EMU_DEPENDENCIES += xwayland qt6wayland
DOLPHIN_EMU_CONF_OPTS += -DENABLE_X11=ON
endif

ifeq ($(BR2_PACKAGE_RECALBOX_HAS_VULKAN),y)
DOLPHIN_EMU_DEPENDENCIES += vulkan-headers
DOLPHIN_EMU_CONF_OPTS += -DENABLE_VULKAN=ON
endif

ifeq ($(BR2_aarch64),y)
DOLPHIN_EMU_CONF_OPTS += -DENABLE_DRM=ON
endif

define DOLPHIN_EMU_POST_INSTALL_TARGET_HOOK
	mv $(TARGET_DIR)/usr/bin/dolphin-emu $(TARGET_DIR)/usr/bin/dolphin-gui
	mv $(TARGET_DIR)/usr/bin/dolphin-emu-nogui $(TARGET_DIR)/usr/bin/dolphin
endef

DOLPHIN_EMU_POST_INSTALL_TARGET_HOOKS += DOLPHIN_EMU_POST_INSTALL_TARGET_HOOK

$(eval $(cmake-package))
