#!/bin/bash

[ "$1" != "start" ] && exit

. /recalbox/scripts/recalbox-utils.sh

do_start() {
  local STEP=$(getStepNumber)
  local ARCH=$(uname -m)

  # Cases - Don't try to detect if already done or if recalbox rgb dual module is loaded
  if [ "$STEP" != "1" ] && ! isCRTLoaded; then
    cd /var
    python "/recalbox/system/hardware/case/manage.py" "" 1 1 0
    # let S05hardware do its job if no case found here
    mount -o remount,rw /boot
    sed -i -E 's/^(case=none:0)/;\1/' /boot/recalbox-boot.conf
  fi

  # Video cards
  [ "$ARCH" = "x86_64" ] && /recalbox/system/hardware/videocard/nvidia-install --early
}

do_start
