#!/bin/bash

# TIC-80 Software Downloader
#
# This script downloads TIC-80 cartridges from https://tic80.com
# Cartridges are downloaded and stored as .tic files in their respective category directory.
# The file name format is as follows:
#   ${cartridgeName} - ${cartridgeId} (${cartridgeDate}).tic

#############
# VARIABLES #
#############

releaseDate=2023.05.01

#############
# FUNCTIONS #
#############

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")

# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")

# chooseCategory
#   asks the user which category of software they want to download and set it as ${categoryChoice}
function chooseCategory {
  PS3="Which category of software do you want to download? "
  select categoryChoice in Games Tech Tools Music WIP Demoscene "All categories"; do
    case ${categoryChoice} in
      Games|Tech|Tools|Music|WIP|Demoscene|"All categories") break;;
    esac
  done
}

# unescapeHTML
#   converts stdin HTML tags to plain text
function unescapeHTML {
  sed 's/&amp;/\&/g; s/&lt;/\</g; s/&gt;/\>/g; s/&quot;/\"/g; s/&ldquo;/\"/g; s/&rdquo;/\"/g;'
}

# unescapeNames
#   converts some characters to others in game names
function unescapeNames {
  sed 's/\?//g; s/\://g; s|\/|-|g; s/>/-/g; s/</-/g; s/&#34;/-/g;  s/&#39;/-/g; s/\*/-/g;'
}

# categoryId <categoryName>
#   outputs the category ID for a given category name
function categoryId {
  local categoryName="$1"
  case ${categoryName} in
    Games) echo 0;;
    Tech) echo 1;;
    Tools) echo 2;;
    Music) echo 3;;
    WIP) echo 4;;
    Demoscene) echo 5;;
    *) echo "Category not found"; break;;
  esac
}

# downloadCartridge <cartridgeId> <cartridgeName> <categoryName>
#   downloads a given cartridge
function downloadCartridge {
  local id=$1
  local name=$2
  local categoryName=$3
  local pageContent=$(curl -sL "https://tic80.com/play?cart=${id}")
  local gametitle=$(echo "${name//[$'\t\r\n ']}" | unescapeNames)
  local pagelink=$(echo "${pageContent}" | sed -n 's|.*href="/cart/\(.*\)">.*|\1|p')
  local createdAt=$(echo "${pageContent}" | sed -n 's|.*added: <span class="date" value="\([[:digit:]]*\)">.*|\1|p')
  local updatedAt=$(echo "${pageContent}" | sed -n 's|.*updated: <span class="date" value="\([[:digit:]]*\)">.*|\1|p')
  if [ -z "${updatedAt}" ]; then
    local timestamp=$(date -d @$((${createdAt} / 1000)) +%F_%H-%M)
  else
    local timestamp=$(date -d @$((${updatedAt:-${createdAt}} / 1000)) +%F_%H-%M)
  fi
  echo -n "Downloading cartridge ${gametitle} in ${categoryName}"
  mkdir -p ${SCRIPTPATH}/${categoryName}
  curl -sLf "https://tic80.com/cart/${pagelink}" -o "${SCRIPTPATH}/${categoryName}/${gametitle} - ${id} (${timestamp}).tic" && echo " [OK]" || echo " [ERROR]"
}

# downloadCategorySoftware <categoryName>
#   downloads all cartridges in a given category
function downloadCategorySoftware {
  local categoryName="$1"
  local categoryId=$(categoryId ${categoryName})
  local categoryPageNumbers=$(curl -sLf "https://tic80.com/play?cat=${categoryId}&sort=2")
  local maxPagesNumber=( $(echo "${categoryPageNumbers}" | grep '<a href="/play?cat=.*>' | tail -n 1 | sed -r 's|.*?>(.+)<.*|\1|g') )

  for (( i = 0; i < ${maxPagesNumber}; i++)); do
    local categoryPageContent=$(curl -sLf "https://tic80.com/play?cat=${categoryId}&sort=2&page=${i}")
    IFS=$'\n'
    local cartridgeNames=( $(echo "${categoryPageContent}" | sed -n 's|.*<h2>\(.*\)</h2>|\1|p' | unescapeHTML) )
    local cartridgeIds=( $(echo "${categoryPageContent}" | sed -n 's|.*href="/play?cart=\([[:digit:]]*\)".*|\1|p') )
    for (( j = 0; j < ${#cartridgeNames[@]}; j++ )); do
      downloadCartridge "${cartridgeIds[$j]}" "${cartridgeNames[$j]}" "${categoryName}"
    done
  done
}

########
# MAIN #
########

echo "recalbox-tic80 ver. ${releaseDate}"

chooseCategory

if [ "${categoryChoice}" = "All categories" ]; then
  for category in Games Tech Tools Music WIP Demoscene; do
    downloadCategorySoftware ${category}
  done
else
  downloadCategorySoftware ${categoryChoice}
fi
