################################################################################
#
# PARALLEL-N64
#
################################################################################

# Commit of 2025/12/04
LIBRETRO_PARALLEL_N64_VERSION = 1da824e13e725a7144f3245324f43d59623974f8
LIBRETRO_PARALLEL_N64_SITE = $(call github,libretro,parallel-n64,$(LIBRETRO_PARALLEL_N64_VERSION))
LIBRETRO_PARALLEL_N64_LICENSE = GPL-3.0

ifeq ($(BR2_PACKAGE_RPI_USERLAND),y)
LIBRETRO_PARALLEL_N64_DEPENDENCIES += rpi-userland
endif

ifeq ($(BR2_PACKAGE_HAS_LIBGLES),y)
LIBRETRO_PARALLEL_N64_DEPENDENCIES += libgles
endif

ifeq ($(BR2_PACKAGE_HAS_LIBGL),y)
LIBRETRO_PARALLEL_N64_DEPENDENCIES += libgl
endif

ifeq ($(BR2_i386)$(BR2_x86_64),y)
LIBRETRO_PARALLEL_N64_DEPENDENCIES += host-nasm
endif

# LTO switched off on PC platforms
# Platform dependent options
LIBRETRO_PARALLEL_N64_CFLAGS = $(COMPILER_COMMONS_CFLAGS_NOLTO)
LIBRETRO_PARALLEL_N64_CXXFLAGS = $(COMPILER_COMMONS_CXXFLAGS_NOLTO)
LIBRETRO_PARALLEL_N64_LDFLAGS = $(COMPILER_COMMONS_LDFLAGS_NOLTO)

ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPIZERO2LEGACY),y)
LIBRETRO_PARALLEL_N64_PLATFORM=unix-rpi3

else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI3)$(BR2_PACKAGE_RECALBOX_TARGET_RPIZERO2),y)
LIBRETRO_PARALLEL_N64_PLATFORM=unix-rpi3-mesa

else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI4),y)
LIBRETRO_PARALLEL_N64_PLATFORM=unix-rpi3-mesa

else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI4_64),y)
LIBRETRO_PARALLEL_N64_PLATFORM=unix-rpi4_64-mesa
LIBRETRO_PARALLEL_N64_SUPP_OPT=HAVE_OPENGL=1 GLES=1 GL_LIB:=-lGLESv2

else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI5_64),y)
LIBRETRO_PARALLEL_N64_PLATFORM=unix-rpi5_64-mesa
LIBRETRO_PARALLEL_N64_SUPP_OPT=HAVE_OPENGL=1 GLES=1 GL_LIB:=-lGLESv2

else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_ODROIDXU4),y)
LIBRETRO_PARALLEL_N64_PLATFORM=odroid
LIBRETRO_PARALLEL_N64_SUPP_OPT=BOARD=ODROID-XU

else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_ODROIDGO2),y)
LIBRETRO_PARALLEL_N64_PLATFORM = odroid
LIBRETRO_PARALLEL_N64_SUPP_OPT = BOARD=ODROIDGO2 HAVE_PARELLEL_RSP=1

else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RG353X),y)
#LIBRETRO_PARALLEL_N64_PLATFORM = unix gles
#LIBRETRO_PARALLEL_N64_SUPP_OPT = HAVE_PARALLEL=1 LIBS=-lmali CPUFLAGS="-DCLASSIC -DARM64 -DARM_FIX"
LIBRETRO_PARALLEL_N64_PLATFORM = odroid
LIBRETRO_PARALLEL_N64_SUPP_OPT = BOARD=ODROIDGO2 HAVE_PARELLEL_RSP=1

else ifeq ($(BR2_x86_64),y)
LIBRETRO_PARALLEL_N64_SUPP_OPT=ARCH=x86_64 HAVE_PARALLEL_RSP=1 HAVE_THR_AL=1
LIBRETRO_PARALLEL_N64_PLATFORM=unix
endif

ifeq ($(BR2_PACKAGE_RECALBOX_HAS_LIBMALI),y)
LIBRETRO_PARALLEL_N64_SUPP_OPT += LIBS=-lmali
endif

LIBRETRO_PARALLEL_N64_DYNAREC = $(BR2_ARCH)

define LIBRETRO_PARALLEL_N64_BUILD_CMDS
	$(SED) "s|-O2|-O3|g" $(@D)/Makefile
	PLATCFLAGS="$(TARGET_CFLAGS)" CFLAGS="$(TARGET_CFLAGS) $(LIBRETRO_PARALLEL_N64_CFLAGS)" \
		CXXFLAGS="$(TARGET_CXXFLAGS) $(LIBRETRO_PARALLEL_N64_CXXFLAGS)" \
		LDFLAGS="$(TARGET_LDFLAGS) $(LIBRETRO_PARALLEL_N64_LDFLAGS)" \
		$(MAKE) CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" -C $(@D)/ -f Makefile \
		platform="$(LIBRETRO_PARALLEL_N64_PLATFORM)" $(LIBRETRO_PARALLEL_N64_SUPP_OPT) \
		WITH_DYNAREC=$(LIBRETRO_PARALLEL_N64_DYNAREC) \
		GIT_VERSION="-$(shell echo $(LIBRETRO_PARALLEL_N64_VERSION) | cut -c 1-8)"
		# HAVE_PARALLEL=1 HAVE_PARALLEL_RSP=1
endef

define LIBRETRO_PARALLEL_N64_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/parallel_n64_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/parallel_n64_libretro.so
endef

$(eval $(generic-package))
