################################################################################
#
# LIBRETRO PPSSPP
#
################################################################################

# Commit of 2025/09/24
LIBRETRO_PPSSPP_VERSION = d43f24dab3b440d82b1ec7ee1c5cc25e0f24510e
LIBRETRO_PPSSPP_SITE = https://github.com/hrydgard/ppsspp
LIBRETRO_PPSSPP_SITE_METHOD=git
LIBRETRO_PPSSPP_GIT_SUBMODULES=y
LIBRETRO_PPSSPP_DEPENDENCIES = ffmpeg snappy zip sdl2 libpng
LIBRETRO_PPSSPP_LICENSE = GPL-2.0
LIBRETRO_PPSSPP_LICENSE_FILES = LICENSE.TXT

LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_C_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_C_ARCHIVE_FINISH=true
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_FINISH=true
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_C_FLAGS="$(COMPILER_COMMONS_CFLAGS_NOLTO) -DEGL_NO_X11=1 -DMESA_EGL_NO_X11_HEADERS=1"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(COMPILER_COMMONS_CXXFLAGS_NOLTO) -DEGL_NO_X11=1 -DMESA_EGL_NO_X11_HEADERS=1"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_LINKER_EXE_FLAGS="$(COMPILER_COMMONS_LDFLAGS_NOLTO)"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
# :: Options
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_FFMPEG=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_DISCORD=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_MINIUPNPC=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_SNAPPY=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_FFMPEG=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_LIBZIP=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_LIBSDL2=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_LIBPNG=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_ZSTD=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_MINIUPNPC=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
# :: Frontends
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_QT_UI=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DMOBILE_DEVICE=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DHEADLESS=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUNITTEST=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DSIMULATOR=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DLIBRETRO=ON
# :: Environments
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_FBDEV=OFF

ifeq ($(BR2_PACKAGE_HAS_LIBGL),y)
LIBRETRO_PPSSPP_DEPENDENCIES += libgl
endif

ifeq ($(BR2_PACKAGE_HAS_LIBGLES),y)
LIBRETRO_PPSSPP_DEPENDENCIES += libgles
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_GLES2=ON
endif

ifeq ($(BR2_PACKAGE_HAS_LIBEGL),y)
LIBRETRO_PPSSPP_DEPENDENCIES += libegl
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_EGL=ON
endif

ifeq ($(BR2_PACKAGE_RECALBOX_HAS_VULKAN),y)
LIBRETRO_PPSSPP_DEPENDENCIES += vulkan-headers
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_VULKAN_DISPLAY_KHR=ON

ifeq ($(BR2_PACKAGE_WAYLAND),y)
LIBRETRO_PPSSPP_DEPENDENCIES += wayland
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_WAYLAND_WSI=ON
else ifeq ($(BR2_PACKAGE_RECALBOX_VIDEO_XORG_SERVER),y)
LIBRETRO_PPSSPP_DEPENDENCIES += xserver_xorg-server
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_X11_VULKAN=ON
endif

endif

# disable X11 if no xorg package
ifeq ($(BR2_PACKAGE_RECALBOX_VIDEO_XORG_SERVER),)
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_X11_VULKAN=OFF
endif

define LIBRETRO_PPSSPP_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/lib/ppsspp_libretro.so $(TARGET_DIR)/usr/lib/libretro/ppsspp_libretro.so
	mkdir -p $(TARGET_DIR)/usr/share/ppsspp
	cp -R $(@D)/assets $(TARGET_DIR)/usr/share/ppsspp/PPSSPP
endef

$(eval $(cmake-package))
