#!/bin/bash
set -e

if [[ $1 == "start" ]];then
  if [[ "$(cat /recalbox/recalbox.arch)" =~ rpi(4|5) ]]; then
    if [[ "$(cat /boot/bootloader.lastupgrade)" != "$(cat /recalbox/recalbox.version)" ]];then
      mount -o remount,rw /boot
      # try only once, avoid infinite reboot
      cp /recalbox/recalbox.version /boot/bootloader.lastupgrade
      echo "S01rpieeprom: checking for bootloader upgrade for $(cat /recalbox/recalbox.version)" >> /boot/hardware.log
      # rpi-eeprom-update returns 1 when available
      if ! rpi-eeprom-update; then
        echo "S01rpieeprom: rpi-eeprom-update says an update is available" >> /boot/hardware.log
        # we double check
        latest=$(rpi-eeprom-update | grep LATEST | awk '{print $8}' | sed 's/(\(.*\))/\1/')
        current=$(rpi-eeprom-update | grep CURRENT | awk '{print $8}' | sed 's/(\(.*\))/\1/')
        if [[ $current != "" ]] && [[ "$current" < "$latest" ]]; then
          echo "S01rpieeprom: Upgrading bootloader from ${current} to ${latest}" >> /boot/hardware.log
          rpi-eeprom-update -a
          echo "The bootloader of your Raspberry Pi has been automatically updated." >> /overlay/.frontend_boot_notif
          mount -o remount,ro /boot
          reboot
        else
          echo "S01rpieeprom: update version is older than current one, something is wrong" >> /boot/hardware.log
        fi
      else
        echo "S01rpieeprom: uploader already up to date" >> /boot/hardware.log
      fi
      mount -o remount,ro /boot
    fi
  fi
fi