################################################################################
#
# TAMALIBRETRO
#
################################################################################

# Commit of 2024/09/23
LIBRETRO_TAMALIBRETRO_VERSION = 67605e4209a025840fcd2f1062d39998e627381c
LIBRETRO_TAMALIBRETRO_SITE = https://github.com/celerizer/tamalibretro
LIBRETRO_TAMALIBRETRO_LICENSE = GPL-2.0

LIBRETRO_TAMALIBRETRO_GIT_SUBMODULES=y
LIBRETRO_TAMALIBRETRO_SITE_METHOD=git

ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI3)$(BR2_PACKAGE_RECALBOX_TARGET_RPIZERO2),y)
LIBRETRO_TAMALIBRETRO_PLATFORM=unix-rpi3
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI4_64),y)
LIBRETRO_TAMALIBRETRO_PLATFORM=unix-rpi4
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI5_64),y)
LIBRETRO_TAMALIBRETRO_PLATFORM=unix-rpi5
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_ODROIDGO2),y)
LIBRETRO_TAMALIBRETRO_PLATFORM=unix-ogo2
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RG353X),y)
LIBRETRO_TAMALIBRETRO_PLATFORM=unix-rg353x
else
LIBRETRO_TAMALIBRETRO_PLATFORM=unix
endif

define LIBRETRO_TAMALIBRETRO_BUILD_CMDS
	CFLAGS="$(TARGET_CFLAGS) $(COMPILER_COMMONS_CFLAGS_SO)" \
		CXXFLAGS="$(TARGET_CXXFLAGS) $(COMPILER_COMMONS_CXXFLAGS_SO)" \
		LDFLAGS="$(TARGET_LDFLAGS) $(COMPILER_COMMONS_LDFLAGS_SO)" \
		$(MAKE) CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" -C $(@D)/ -f Makefile platform="unix" \
		GIT_VERSION="-$(shell echo $(LIBRETRO_TAMALIBRETRO_VERSION) | cut -c 1-8)"
endef

define LIBRETRO_TAMALIBRETRO_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/tamalibretro_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/tamalibretro_libretro.so
endef

$(eval $(generic-package))
