; ===========================
; themehospital
; ===========================

; all keys can be overridden for a particular board using key.<boardtag>
; example:
;   priority = 0
;   priority.rpi4 = 3
; Complete sections may be overridden. In such cases, all key from the global section are ignored,
; you must redefine them all
; example
; [core.0]
; [core.0.rpi4]
; Board tags are defined by BR2_PACKAGE_RECALBOX_TARGET_<tag>

[system]
uuid = "f992a6b6-f439-43f8-94bb-db71b285fba1"
name = "themehospital"
fullname = "Theme Hospital"
theme.folder = "themehospital"
roms.folder = "%ROOT%/ports/Theme Hospital"
screenscraper.id = 135
doc.link.fr = "https://wiki.recalbox.com/fr/emulators/ports/theme-hospital"
doc.link.en = "https://wiki.recalbox.com/en/emulators/ports/theme-hospital"
doc.link.es = "https://wiki.recalbox.com/es/emulators/ports/theme-hospital"
port = 1
readonly = 0
downloader = 1
icon.unicode = $F2fa
extension.types = "*=file"

[properties]
type = port
device.pad = no
device.keyboard = optional
device.mouse = mandatory
device.lightgun = no
release.date = "1997-02"
manufacturer = "Bullfrog"
retroachievements = 0
crt.multiresolution = 0
crt.multiregion = 0

[core.0]
package = BR2_PACKAGE_CORSIXTH
priority = 1
emulator = "corsixth"
core = "corsixth"
extensions = "files:Theme Hospital (1997).zip"
netplay = 0
softpatching = 0
compatibility = high
speed = high
