################################################################################
#
# fbv - Recalbox version
#
################################################################################

RECALBOX_FBV_VERSION = custom
RECALBOX_FBV_SITE = $(TOPDIR)/../projects/recalbox-fbv
RECALBOX_FBV_SITE_METHOD = local
RECALBOX_FBV_LICENSE = GPL-2.0
RECALBOX_FBV_LICENSE_FILES = COPYING
RECALBOX_FBV_DEPENDENCIES = libpng jpeg giflib

RECALBOX_FBV_CONF_OPTS += -DCMAKE_C_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
RECALBOX_FBV_CONF_OPTS += -DCMAKE_C_ARCHIVE_FINISH=true
RECALBOX_FBV_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
RECALBOX_FBV_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_FINISH=true
RECALBOX_FBV_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
RECALBOX_FBV_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
RECALBOX_FBV_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
RECALBOX_FBV_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
RECALBOX_FBV_CONF_OPTS += -DCMAKE_C_FLAGS="$(COMPILER_COMMONS_CFLAGS_EXE)"
RECALBOX_FBV_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(COMPILER_COMMONS_CXXFLAGS_EXE)"
RECALBOX_FBV_CONF_OPTS += -DCMAKE_LINKER_EXE_FLAGS="$(COMPILER_COMMONS_LDFLAGS_EXE)"
RECALBOX_FBV_CONF_OPTS += -DOPTION_RECALBOX_PRODUCTION_BUILD=true

define RECALBOX_FBV_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/fbv2 $(TARGET_DIR)/usr/bin/
endef

$(eval $(cmake-package))
